package textures;


/*
 It just holds the different textures representing the different color in the Blender map........
 The blender map ha 4 colors blue, red, green and black which represent the 4 terrain textures present in our textures.............
*/
public class TerrainTexturePack {

	private TerrainTextures backgroundTexture;                            // Background texture(black) variable of type terrain texture....................
	private TerrainTextures rTexture;                                    // Red texture variable of type terrain texture....................
	private TerrainTextures gTexture;                                   // Green texture variable of type terrain texture....................
	private TerrainTextures bTexture;                                  //// Blue texture variable of type terrain texture....................
	
	
	
	
	
	//Constructor of this class which takes the 4 Terrain textures and assign it to the variables for furrther a do.............................................
	public TerrainTexturePack(TerrainTextures backgroundTexture, TerrainTextures rTexture, TerrainTextures gTexture,
			TerrainTextures bTexture) {
		super();
		this.backgroundTexture = backgroundTexture;                                     //Assign background texture, grass in our case...............................
		this.rTexture = rTexture;                                                       // assign red texture, dirt in our case........................ 
		this.gTexture = gTexture;                                                       // assign green texture, mud in our case.......................
		this.bTexture = bTexture;                                                       // assign blue texture, path in our case.......................
	}
	
	
	
	
	//Getters to get these above variables whenever needed.............................................................
	public TerrainTextures getBackgroundTexture() {                                    // Getter for background texture......................
		return backgroundTexture;
	}
	public TerrainTextures getrTexture() {                                              // Getter for red texture......................
		return rTexture;
	}
	public TerrainTextures getgTexture() {                                               // Getter for green texture......................
		return gTexture;
	}
	public TerrainTextures getbTexture() {                                                // Getter for blue texture......................
		return bTexture;
	}

	
	
}
